/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package untitled.folder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

class AppTest {
            App classUnderTest = new App();

    @Test void appHasAGreeting() {
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        assertEquals("Hello World!", classUnderTest.getGreeting());
    }

    // Create a test that tests a non existing method. This should return the number of words in a list that begin with the letter E
    // Created test that calls non existent method called the method with a list 0 strings
    // Expect method th return an Integer
    // Expect method to return 2

    @Test
    public void wordsThatStartWithE_HappyPath() {
        List<String> strings = new ArrayList<String>(Arrays.asList("Cat", "Dog", "every", "eye", "open"));
    long result = classUnderTest.wordsThatStartWithE(strings);
        assertEquals(2L, result);
    }
}
    // You can also write tests for edge cases